### ISSUE TITLE
[US 15] : Permettre à l'utilisateur (agriculteur) de mettre à jour la disponibilité et la quantité de ses produits

### ISSUE THREAD

**Issue by Falettiattendre** [IUT-Blagnac/sae3-01-devapp-g2b-12#20]
- [x] Écrire un test
- [x] Coder
- [x] Écrire la doc
### US associée
- #58

**Comment by ghost** [comment]
@Falettiattendre @ludovic-estival pour ça il faudra que lorsqu'on affiche des produits on prennent que  ceux qui on STOCK > 0.
